<?php
namespace Common\Component;
class CityCopyComponent{
	 static public function getCityList(){
		return array(
				array('id' => 110100, 'cityName' => '市辖区', 'pinyin' => 'shixiaqu', 'simplePinyin' => 'sxq', 'initial' => 'S', 'areaCode' => '010'),
				array('id' => 120100, 'cityName' => '市辖区', 'pinyin' => 'shixiaqu', 'simplePinyin' => 'sxq', 'initial' => 'S', 'areaCode' => '022'),
				array('id' => 130100, 'cityName' => '石家庄市', 'pinyin' => 'shijiazhuangshi', 'simplePinyin' => 'sjzs', 'initial' => 'S', 'areaCode' => '0311'),
				array('id' => 130200, 'cityName' => '唐山市', 'pinyin' => 'tangshanshi', 'simplePinyin' => 'tss', 'initial' => 'T', 'areaCode' => '0315'),
				array('id' => 140100, 'cityName' => '太原市', 'pinyin' => 'taiyuanshi', 'simplePinyin' => 'tys', 'initial' => 'T', 'areaCode' => '0351'),
				array('id' => 150100, 'cityName' => '呼和浩特市', 'pinyin' => 'huhehaoteshi', 'simplePinyin' => 'hhhts', 'initial' => 'H', 'areaCode' => '0471'),
				array('id' => 150200, 'cityName' => '包头市', 'pinyin' => 'baotoushi', 'simplePinyin' => 'bts', 'initial' => 'B', 'areaCode' => '0472'),
				array('id' => 210100, 'cityName' => '沈阳市', 'pinyin' => 'shenyangshi', 'simplePinyin' => 'sys', 'initial' => 'S', 'areaCode' => '024'),
				array('id' => 210200, 'cityName' => '大连市', 'pinyin' => 'dalianshi', 'simplePinyin' => 'dls', 'initial' => 'D', 'areaCode' => '0411'),
				array('id' => 220100, 'cityName' => '长春市', 'pinyin' => 'changchunshi', 'simplePinyin' => 'ccs', 'initial' => 'C', 'areaCode' => '0431'),
				array('id' => 230100, 'cityName' => '哈尔滨市', 'pinyin' => 'haerbinshi', 'simplePinyin' => 'hebs', 'initial' => 'H', 'areaCode' => '0451'),
				array('id' => 310100, 'cityName' => '市辖区', 'pinyin' => 'shixiaqu', 'simplePinyin' => 'sxq', 'initial' => 'S', 'areaCode' => ''),
				array('id' => 320100, 'cityName' => '南京市', 'pinyin' => 'nanjingshi', 'simplePinyin' => 'njs', 'initial' => 'N', 'areaCode' => '025'),
				array('id' => 320200, 'cityName' => '无锡市', 'pinyin' => 'wuxishi', 'simplePinyin' => 'wxs', 'initial' => 'W', 'areaCode' => '0510'),
				array('id' => 320500, 'cityName' => '苏州市', 'pinyin' => 'suzhoushi', 'simplePinyin' => 'szs', 'initial' => 'S', 'areaCode' => '0512'),
				array('id' => 330100, 'cityName' => '杭州市', 'pinyin' => 'hangzhoushi', 'simplePinyin' => 'hzs', 'initial' => 'H', 'areaCode' => '0571'),
				array('id' => 330200, 'cityName' => '宁波市', 'pinyin' => 'ningboshi', 'simplePinyin' => 'nbs', 'initial' => 'N', 'areaCode' => '0574'),
				array('id' => 340100, 'cityName' => '合肥市', 'pinyin' => 'hefeishi', 'simplePinyin' => 'hfs', 'initial' => 'H', 'areaCode' => '0551'),
				array('id' => 350100, 'cityName' => '福州市', 'pinyin' => 'fuzhoushi', 'simplePinyin' => 'fzs', 'initial' => 'F', 'areaCode' => '0591'),
				array('id' => 350200, 'cityName' => '厦门市', 'pinyin' => 'xiamenshi', 'simplePinyin' => 'xms', 'initial' => 'X', 'areaCode' => '0592'),
				array('id' => 350500, 'cityName' => '泉州市', 'pinyin' => 'quanzhoushi', 'simplePinyin' => 'qzs', 'initial' => 'Q', 'areaCode' => '0595'),
				array('id' => 360100, 'cityName' => '南昌市', 'pinyin' => 'nanchangshi', 'simplePinyin' => 'ncs', 'initial' => 'N', 'areaCode' => '0791'),
				array('id' => 370100, 'cityName' => '济南市', 'pinyin' => 'jinanshi', 'simplePinyin' => 'jns', 'initial' => 'J', 'areaCode' => '0531'),
				array('id' => 370200, 'cityName' => '青岛市', 'pinyin' => 'qingdaoshi', 'simplePinyin' => 'qds', 'initial' => 'Q', 'areaCode' => '0532'),
				array('id' => 370600, 'cityName' => '烟台市', 'pinyin' => 'yantaishi', 'simplePinyin' => 'yts', 'initial' => 'Y', 'areaCode' => '0535'),
				array('id' => 410100, 'cityName' => '郑州市', 'pinyin' => 'zhengzhoushi', 'simplePinyin' => 'zzs', 'initial' => 'Z', 'areaCode' => '0371'),
				array('id' => 420100, 'cityName' => '武汉市', 'pinyin' => 'wuhanshi', 'simplePinyin' => 'whs', 'initial' => 'W', 'areaCode' => '027'),
				array('id' => 430100, 'cityName' => '长沙市', 'pinyin' => 'changshashi', 'simplePinyin' => 'css', 'initial' => 'C', 'areaCode' => '0716'),
				array('id' => 440100, 'cityName' => '广州市', 'pinyin' => 'guangzhoushi', 'simplePinyin' => 'gzs', 'initial' => 'G', 'areaCode' => '020'),
				array('id' => 440300, 'cityName' => '深圳市', 'pinyin' => 'shenzhenshi', 'simplePinyin' => 'szs', 'initial' => 'S', 'areaCode' => '0755'),
				array('id' => 440600, 'cityName' => '佛山市', 'pinyin' => 'foshanshi', 'simplePinyin' => 'fss', 'initial' => 'F', 'areaCode' => '0757'),
				array('id' => 441900, 'cityName' => '东莞市', 'pinyin' => 'dongguanshi', 'simplePinyin' => 'dgs', 'initial' => 'D', 'areaCode' => '0769'),
				array('id' => 450100, 'cityName' => '南宁市', 'pinyin' => 'nanningshi', 'simplePinyin' => 'nns', 'initial' => 'N', 'areaCode' => '0771'),
				array('id' => 500100, 'cityName' => '市辖区', 'pinyin' => 'shixiaqu', 'simplePinyin' => 'sxq', 'initial' => 'S', 'areaCode' => '023'),
				array('id' => 510100, 'cityName' => '成都市', 'pinyin' => 'chengdushi', 'simplePinyin' => 'cds', 'initial' => 'C', 'areaCode' => '028'),
				array('id' => 520100, 'cityName' => '贵阳市', 'pinyin' => 'guiyangshi', 'simplePinyin' => 'gys', 'initial' => 'G', 'areaCode' => '0851'),
				array('id' => 530100, 'cityName' => '昆明市', 'pinyin' => 'kunmingshi', 'simplePinyin' => 'kms', 'initial' => 'K', 'areaCode' => '0871'),
				array('id' => 610100, 'cityName' => '西安市', 'pinyin' => 'xianshi', 'simplePinyin' => 'xas', 'initial' => 'X', 'areaCode' => '029'),
				array('id' => 620100, 'cityName' => '兰州市', 'pinyin' => 'lanzhoushi', 'simplePinyin' => 'lzs', 'initial' => 'L', 'areaCode' => '0931'),
				array('id' => 650100, 'cityName' => '乌鲁木齐市', 'pinyin' => 'wulumuqishi', 'simplePinyin' => 'wlmqs', 'initial' => 'W', 'areaCode' => '0991'),
		);
	}}